### PR TITLE
FOIA-55 config normalize

### PR DESCRIPTION
**Pull request by benjifisher**
I started by importing the database from the UAT site.

The config changes all come from `drush cr && drush cim` followed by `drush cr && drush cex`. I separated them into three commits based on the type of change.

I am not sure why only one of the webforms changes this way. All of the other `webform.webform.*.yml` files have the `uuid` entry at the end. I did check that the added keys are the defaults when I add a new webform.

It is a little out of scope for this issue, but I also fixed a problem with `composer.json` that was caught by `blt doctor`.

### CODE REVIEW

**Comment by ba66e77** [comment]
Good catch on the composer.json having drupal-drush twice. Looks like that stemmed from a merge conflict when BLT was updated some time back.

On the number of changes in this, the only configs I'm seeing updated after running `blt sync; drush cim; drush cex` are the few below. Did you manually review/edit all the others?

```
	modified:   config/default/field.field.node.total_annual_data.field_equiv_full_time_employees.yml
	modified:   config/default/field.field.node.total_annual_data.field_full_time_employees.yml
	modified:   config/default/field.field.node.total_annual_data.field_processing_costs.yml
	modified:   config/default/field.storage.node.field_equiv_full_time_employees.yml
	modified:   config/default/field.storage.node.field_full_time_employees.yml
	modified:   config/default/field.storage.node.field_processing_costs.yml
	modified:   config/default/webform.webform.doj_enrd.yml
```

**Comment by benjifisher** [comment]
> Looks like that stemmed from a merge conflict when BLT was updated some time back.

Right, I noticed that, too:

```
$ git log -1 45ceec619b
commit 45ceec619bac4d8c0eca10eb6b710c03010e42c5
Author: Brock Fanning <brockfanning@gmail.com>
Date:   Wed May 8 19:08:14 2019 +0000

    DOJ-884259: A ton of files that blt changed when it updated itself.
```

Credit to catching the mistake goes to `blt doctor`. I mentioned that in the extended commit message.

If you look at the individual commits in this PR, you will see that the 7 files you mention are the ones changed in the first three commits (before the one that fixes `composer.json`). As I wrote on [FOIA-55|https://acquiaps.atlassian.net/browse/FOIA-55],

> Note that the first few commits are enough to get `blt dci` to finish cleanly after importing the database from UAT. The last several commits are only needed to import config cleanly after building a clean site with `blt drupal:install`.

> Did you manually review/edit all the others?

Not only did I review them, I took pains to break them into separate commits so that they are easier to review. For example, it is a lot easier to review 02ea53859613196bf7ffff0b78440ab4e2f804a4 and 193dc8e7db62ae7acba014f41b9a5c360f0bf4ac, both of which affect the same file, separately than to look at the combined diff.

**Comment by bemarlan** [comment]
I'm going to cherry-pick and plan to merge the first four commits, which is mvp for fixing the config mismatch issue. I will submit information to DOJ developers on normalizing the other config files.

**Comment by bemarlan** [comment]
Closing this PR in favor of [PR 28](https://github.com/acquia-pso/foia-api-enhancements/pull/28) which includes the first four commits on this branch.

**Pull request closed without merging**
